---
- name: check if node exporter exist
  stat:
    path: "{{ exporter_bin }}"
  register: __check_exporter_present

- name: create monitoring user
  user:
    name: "{{ monitoring_user }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false

- name: create node exporter config dir
  file:
    path: "{{ exporter_dir_conf }}"
    state: directory
    owner: "{{ monitoring_user }}"
    group: "{{ monitoring_group }}"

- name: if node exporter exist get version
  shell: "cat {{ exporter_dir_service }} | grep Version | sed s/'.*Version '//g"
  when: __check_exporter_present.stat.exists == true
  changed_when: false
  register: __get_exporter_version

- name: download and unzip node exporter if not exist
  unarchive:
    src: "{{ exporter_url_file }}"
    dest: /tmp/
    remote_src: yes
    validate_certs: no

- name: move the binary to the final destination
  copy:
    src: "/tmp/node_exporter-{{ exporter_version }}.linux-amd64/node_exporter"
    dest: "{{ exporter_bin }}"
    owner: "{{ monitoring_user }}"
    group: "{{ monitoring_group }}"
    mode: 0755
    remote_src: yes
  when: __check_exporter_present.stat.exists == false or not __get_exporter_version.stdout == exporter_version

- name: clean
  file:
    path: /tmp/node_exporter-{{ exporter_version }}.linux-amd64/
    state: absent

- name: install service
  template:
    src: node_exporter.service.j2
    dest: "{{ exporter_dir_service }}"
    owner: root
    group: root
    mode: 0755
  notify: reload_daemon_and_restart_exporter

- meta: flush_handlers
- name: service always started
  systemd:
    name: "{{ service_name }}"
    state: started
    enabled: yes
